blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/mihonapp/mihon/issues/new/choose
    about: Issues and requests about the app itself should be opened in Mihon's repository instead
  - name: 📦 Extension list
    url: https://keiyoushi.github.io/extensions
    about: List of all available extensions with download links
  - name: 🖥️ Mihon website
    url: https://mihon.app/docs/guides/troubleshooting/
    about: Guides, troubleshooting, and answers to common questions
