name: CI

on:
    push:
        branches:
            - master
        paths-ignore:
            - '**.md'
            - '.github/workflows/issue_moderator.yml'
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to run the workflow from'
                required: true
                default: 'master'

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

env:
    CI_CHUNK_SIZE: 1

jobs:
    prepare:
        name: Prepare job
        runs-on: ubuntu-latest
        outputs:
            individualMatrix: ${{ steps.generate-matrices.outputs.individualMatrix }}
            multisrcMatrix: ${{ steps.generate-matrices.outputs.multisrcMatrix }}
        env:
            CI_MODULE_GEN: true
        steps:
            - name: Clone repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch || 'master' }}

            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v2

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Generate multisrc sources
              run: ./gradlew :multisrc:generateExtensions

            - name: Get number of modules
              run: |
                  set -x
                  ./gradlew -q projects | grep '.*extensions\:\(individual\|multisrc\)\:.*\:.*' > projects.txt
                  
                  echo "NUM_INDIVIDUAL_MODULES=$(cat projects.txt | grep '.*\:individual\:.*' | wc -l)" >> $GITHUB_ENV
                  echo "NUM_MULTISRC_MODULES=$(cat projects.txt | grep '.*\:multisrc\:.*' | wc -l)" >> $GITHUB_ENV

            - id: generate-matrices
              name: Create output matrices
              uses: actions/github-script@v7
              with:
                  script: |
                      const numIndividualModules = process.env.NUM_INDIVIDUAL_MODULES;
                      const numMultisrcModules = process.env.NUM_MULTISRC_MODULES;
                      const chunkSize = process.env.CI_CHUNK_SIZE;
                      
                      const numIndividualChunks = Math.ceil(numIndividualModules / chunkSize);
                      const numMultisrcChunks = Math.ceil(numMultisrcModules / chunkSize);
                      
                      console.log(`Individual modules: ${numIndividualModules} (${numIndividualChunks} chunks of ${chunkSize})`);
                      console.log(`Multi-source modules: ${numMultisrcModules} (${numMultisrcChunks} chunks of ${chunkSize})`);
                      
                      core.setOutput('individualMatrix', { 'chunk': [...Array(numIndividualChunks).keys()] });
                      core.setOutput('multisrcMatrix', { 'chunk': [...Array(numMultisrcChunks).keys()] });

    build_multisrc:
        name: Build multisrc modules
        needs: prepare
        runs-on: ubuntu-latest
        strategy:
            matrix: ${{ fromJSON(needs.prepare.outputs.multisrcMatrix) }}
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch || 'master' }}

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Prepare signing key
              if: github.repository == 'Clouddark75/tachiyomi-unofficial-extensions'
              run: |
                  echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Generate sources from the multi-source library
              env:
                  CI_MODULE_GEN: "true"
              run: ./gradlew :multisrc:generateExtensions

            - name: Build extensions (chunk ${{ matrix.chunk }})
              env:
                  CI_MULTISRC: "true"
                  CI_CHUNK_NUM: ${{ matrix.chunk }}
                  ALIAS: ${{ secrets.ALIAS }}
                  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
                  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
              run: ./gradlew assembleRelease

            - name: Upload APKs (chunk ${{ matrix.chunk }})
              uses: actions/upload-artifact@v4
              if: github.repository == 'Clouddark75/tachiyomi-unofficial-extensions'
              with:
                  name: "multisrc-apks-${{ matrix.chunk }}"
                  path: "**/*.apk"
                  retention-days: 1

            - name: Clean up CI files
              if: github.repository == 'Clouddark75/tachiyomi-unofficial-extensions'
              run: rm -f signingkey.jks

    build_individual:
        name: Build individual modules
        needs: prepare
        runs-on: ubuntu-latest
        strategy:
            matrix: ${{ fromJSON(needs.prepare.outputs.individualMatrix) }}
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch || 'master' }}

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Prepare signing key
              if: github.repository == 'Clouddark75/tachiyomi-unofficial-extensions'
              run: |
                  echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Build extensions (chunk ${{ matrix.chunk }})
              env:
                  CI_MULTISRC: "false"
                  CI_CHUNK_NUM: ${{ matrix.chunk }}
                  ALIAS: ${{ secrets.ALIAS }}
                  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
                  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
              run: ./gradlew assembleRelease

            - name: Upload APKs (chunk ${{ matrix.chunk }})
              uses: actions/upload-artifact@v4
              if: github.repository == 'Clouddark75/tachiyomi-unofficial-extensions'
              with:
                  name: "individual-apks-${{ matrix.chunk }}"
                  path: "**/*.apk"
                  retention-days: 1

            - name: Clean up CI files
              if: github.repository == 'Clouddark75/tachiyomi-unofficial-extensions'
              run: rm -f signingkey.jks

    publish_repo:
        name: Publish repo
        needs:
            - build_multisrc
            - build_individual
        if: github.repository == 'Clouddark75/tachiyomi-unofficial-extensions'
        runs-on: ubuntu-latest
        steps:
            - name: Download APK artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ~/apk-artifacts
                  pattern: "*-apks-*"
                  merge-multiple: true

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin

            - name: Checkout repo branch
              uses: actions/checkout@v4
              with:
                  ref: repo
                  path: repo

            - name: Create repo artifacts
              run: |
                  cd repo
                  chmod +x ../.github/scripts/move-apks.sh
                  chmod +x ../.github/scripts/create-repo.sh
                  ../.github/scripts/move-apks.sh
                  
                  # Download inspector with better error handling
                  INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/tachiyomiorg/tachiyomi-extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
                  if [ "$INSPECTOR_LINK" != "null" ]; then
                      curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
                      java -jar ./Inspector.jar "apk" "output.json" "tmp"
                  else
                      echo "Warning: Could not download Inspector"
                  fi
                  
                  ../.github/scripts/create-repo.sh

            - name: Deploy repo
              run: |
                  cd repo
                  chmod +x ../.github/scripts/commit-repo.sh
                  ../.github/scripts/commit-repo.sh
